@startuml
title Vista de Código - Mailer Client\nAdapter SMTP
skinparam classAttributeIconSize 0
left to right direction
interface "IMailSender" as iface  {
  +enviar(correo): DeliveryResult
  +reintentar(idEnvio): DeliveryResult
}
class "PostfixSmtpAdapter" as smtp <<Adapter>> {
  -host: String
  -port: int
  --
  +enviar(correo): DeliveryResult
  +reintentar(idEnvio): DeliveryResult
}
class "AwsSesAdapter" as ses <<Adapter Futuro>> {
  +enviar(correo): DeliveryResult
}
class "CorreoInstitucional" as msg  {
  -destinatario: String
  -asunto: String
  -htmlBody: String
  -correlationId: String
}
class "DeliveryResult" as res <<DTO>> {
  +enviado: boolean
  +mensaje: String
  +idEnvio: String
}
smtp ..|> iface
ses ..|> iface
smtp --> msg : envía
smtp ..> res
@enduml